"use client";
import { useState, useEffect } from "react";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import GlobalHeader from "@/components/GlobalHeader";
import { AuthProvider } from "@/components/auth-context";
import { useCounterStore } from '../store/useCounterStore'

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata = {
// 	title: "ComboStore",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

	const fetchSettings = useCounterStore((state) => state.fetchSettings);

	useEffect(() => {
		fetchSettings();
	}, [fetchSettings]);



	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-w-screen min-h-screen`}>
				<AuthProvider>
					<div className={`flex min-h-screen w-screen`}>
						<Sidebar />
						<main className="flex-1 bg-gray-300">
							<GlobalHeader />

							<div className="">{children}</div>
						</main>
					</div>

				</AuthProvider>





			</body>
		</html>
	);
}
